### ISSUE TITLE
Display parsed simulation status

### ISSUE THREAD

**Issue by Zehvogel** [key4hep/eede#47]
At the moment the simulation status is displayed as a number e.g.

![image](https://github.com/key4hep/eede/assets/12029880/96f39b2c-72d1-47ba-b685-3f248c035122)

which is not very useful as the simulation status is a bit-field. It would be much more useful to list the set states (Overlay, Simulation, etc.). If that takes to much space then maybe show them on mouse-over or smth like that.

**Comment by Zehvogel** [comment]
I would even be happy with just a comma separated list of the indices of the set bits e.g.: `simstat: 1, 3, 8`

**Comment by brauliorivas** [comment]
> which is not very useful as the simulation status is a bit-field. It would be much more useful to list the set states (Overlay, Simulation, etc.). If that takes to much space then maybe show them on mouse-over or smth like that.

Hi @Zehvogel, #59 is about showing more information about any object when mouse over. So, in this [commit](https://github.com/key4hep/eede/pull/59/commits/92cc302c66e0bd78c518488698bd6fe1afaf1aaa), it is also showing the `SimulationStatus` from the `MCParticle`. It will show the `state` according to this [file](https://github.com/key4hep/eede/pull/59/files#diff-f4aac86a94ed6cd23c85830bcf07a64aeb572c74f2bd5a4ec088c72c22c4b6e7), and in case the value isn't in the file, the number is shown instead.
