### ISSUE TITLE
Making a release 0.1

### ISSUE THREAD

**Issue by kjvbrt** [key4hep/eede#49]
Hi :)

Since #43 and #48 are interconnected, and #43 needs some more work which will be done later, I would like to have a release. I suggest to have release 0.1 and have it permanently deployed.

**Comment by brauliorivas** [comment]
Nice. So, would you like to have the release now? or wait for #43 and #48 to be merged and then have a release? If the second is the case, we could wait for both PR's to be merged into `main` and push to `release` branch the changes. We would only need to create a new branch from `main`, called `release` and it will be automatically deployed (I can do it). If not, then I will create the branch before that gets merged.

**Comment by brauliorivas** [comment]
Release deployed!

https://key4hep.github.io/eede/release/

**Comment by tmadlener** [comment]
Done and deployed
