### ISSUE TITLE
How to filter out overlay particles?

### ISSUE THREAD

**Issue by Zehvogel** [key4hep/eede#84]
I want to view the MC particle tree of my file and I want to be able to filter out all particles where the overlay flag is set.
I am unable to find the right filter settings for that.

The file: 
[eLpR_15176_0_tiny.truejet.edm4hep.json](https://github.com/user-attachments/files/16796194/eLpR_15176_0_tiny.truejet.edm4hep.json)

**Comment by tmadlener** [comment]
In principle you should be able to select the `Overlay` box from the simulation status and then simply invert the filter. However, currently I need #83 for getting the proper filter box to display in the first place. And then it doesn't seem to work as expected.

**Comment by brauliorivas** [comment]
Hey @Zehvogel, did you try this?
![Selection_002](https://github.com/user-attachments/assets/269d3211-2716-43f7-bf0b-d451e3792ba5)


I only selected `Overlay`, then inverted the filters, and seems to be working.

**Comment by Zehvogel** [comment]
I am relatively sure that I tried exactly that at the time and it did not work, but now it looks like it works
